# Generated by Django 2.0.2 on 2020-05-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='1', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(default='1', on_delete=True, to='app.Grade'),
        ),
    ]
